# Generated by Django 2.0.1 on 2018-01-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attero', '0002_note_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='pub_date',
            new_name='added',
        ),
        migrations.AddField(
            model_name='note',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
