# Generated by Django 2.0.1 on 2018-01-10 01:45

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attero', '0003_auto_20180110_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='attero.Task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attero.Project')),
            ],
        ),
    ]
