# Generated by Django 2.0.1 on 2018-01-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attero', '0007_auto_20180110_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
    ]
