# Generated by Django 2.0.1 on 2018-01-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attero', '0009_auto_20180110_0503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_Project', 'Can view Project'),)},
        ),
    ]
