# Generated by Django 2.0.1 on 2018-02-11 23:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('attero', '0013_auto_20180211_2304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='NoteTemplate',
        ),
    ]
